from __future__ import annotations

import numpy as np
from scipy.ndimage import gaussian_filter
import scipy.interpolate as interpolate
from typing import TYPE_CHECKING

from moonbot_envs.custom_lab_envs.terrains.utils import height_field_to_mesh
from isaaclab.terrains.trimesh.utils import make_plane

if TYPE_CHECKING:
    from moonbot_envs.custom_lab_envs.terrains.config import hf_terrains_cfg


@height_field_to_mesh
def wave_terrain(difficulty: float, cfg: hf_terrains_cfg.HfWaveTerrainCfg) -> np.ndarray:
    # Validate input parameters
    if cfg.num_waves < 0:
        raise ValueError(f"Number of waves must be a positive integer. Got: {cfg.num_waves}.")

    # Calculate terrain dimensions and amplitude
    amplitude = cfg.amplitude_range[0] + difficulty * (cfg.amplitude_range[1] - cfg.amplitude_range[0])
    width_pixels = int(cfg.size[0] / cfg.horizontal_scale)
    length_pixels = int(cfg.size[1] / cfg.horizontal_scale)
    amplitude_pixels = int(0.5 * amplitude / cfg.vertical_scale)

    # Create coordinate grid
    x = np.arange(0, width_pixels)
    y = np.arange(0, length_pixels)
    xx, yy = np.meshgrid(x, y, indexing='ij')

    # Adjust wave parameters based on smoothness
    smooth_factor = cfg.smoothness

    # Reduce wave count for smoother terrain
    num_waves_factor = 0.8 + 0.4 * (1 - smooth_factor)
    num_waves = max(1, int(cfg.num_waves * num_waves_factor))

    # Initialize height field
    hf_raw = np.zeros_like(xx, dtype=np.float32)

    # Extract range parameters
    min_wave_scale, max_wave_scale = cfg.wave_scale_range
    min_amp_ratio, max_amp_ratio = cfg.amplitude_ratio_range

    # Generate each wave component
    for _ in range(num_waves):
        # Calculate wavelength scale with smoothness adjustment
        wave_scale = min_wave_scale + smooth_factor * (max_wave_scale - min_wave_scale)
        wave_scale += (1 - smooth_factor) * np.random.rand() * (max_wave_scale - min_wave_scale)

        # Random wave direction and phase
        wave_phase = np.random.rand() * 2 * np.pi
        direction = np.random.rand() * 2 * np.pi
        dir_x, dir_y = np.cos(direction), np.sin(direction)

        # Calculate amplitude with smoothness adjustment
        amp_ratio = min_amp_ratio + smooth_factor * (max_amp_ratio - min_amp_ratio)
        amp_ratio += (1 - smooth_factor) * np.random.rand() * (max_amp_ratio - min_amp_ratio)
        wave_amp = amplitude_pixels * amp_ratio

        # Calculate wave projection
        base_wavelength = length_pixels / cfg.num_waves
        proj_dist = (xx * dir_x + yy * dir_y) * (2 * np.pi / (base_wavelength * wave_scale))
        wave = wave_amp * np.sin(proj_dist + wave_phase)

        # Add per-wave noise (intensity reduced for smoother terrain)
        noise_factor = cfg.per_wave_noise * (1 - smooth_factor)
        noise = noise_factor * wave_amp * (np.random.rand(*xx.shape) - 0.5)
        hf_raw += wave + noise

    # Add global noise (intensity reduced for smoother terrain)
    global_noise_factor = cfg.global_noise * (1 - smooth_factor)
    global_noise = global_noise_factor * difficulty * amplitude_pixels * (np.random.rand(*xx.shape) - 0.5)
    hf_raw += global_noise

    # Apply Gaussian blur for high smoothness levels
    if cfg.use_gaussian_blur and smooth_factor > 0.3:
        from scipy.ndimage import gaussian_filter
        # Calculate sigma based on smoothness (more smoothing at higher values)
        sigma_min, sigma_max = cfg.blur_sigma_range
        sigma = sigma_min + (sigma_max - sigma_min) * smooth_factor
        hf_raw = gaussian_filter(hf_raw, sigma=sigma)

    # Discretize height values
    return np.rint(hf_raw).astype(np.int16)



@height_field_to_mesh
def origin_wave_terrain(difficulty: float, cfg: hf_terrains_cfg.HfWaveTerrainCfg) -> np.ndarray:
    r"""Generate a terrain with a wave pattern.

    The terrain is a flat platform at the center of the terrain with a wave pattern. The wave pattern
    is generated by adding sinusoidal waves based on the number of waves and the amplitude of the waves.

    The height of the terrain at a point :math:`(x, y)` is given by:

    .. math::

        h(x, y) =  A \left(\sin\left(\frac{2 \pi x}{\lambda}\right) + \cos\left(\frac{2 \pi y}{\lambda}\right) \right)

    where :math:`A` is the amplitude of the waves, :math:`\lambda` is the wavelength of the waves.

    .. image:: ../../_static/terrains/height_field/wave_terrain.jpg
       :width: 40%
       :align: center

    Args:
        difficulty: The difficulty of the terrain. This is a value between 0 and 1.
        cfg: The configuration for the terrain.

    Returns:
        The height field of the terrain as a 2D numpy array with discretized heights.
        The shape of the array is (width, length), where width and length are the number of points
        along the x and y axis, respectively.

    Raises:
        ValueError: When the number of waves is non-positive.
    """
    # check number of waves
    if cfg.num_waves < 0:
        raise ValueError(f"Number of waves must be a positive integer. Got: {cfg.num_waves}.")

    # resolve terrain configuration
    amplitude = cfg.amplitude_range[0] + difficulty * (cfg.amplitude_range[1] - cfg.amplitude_range[0])
    # switch parameters to discrete units
    # -- terrain
    width_pixels = int(cfg.size[0] / cfg.horizontal_scale)
    length_pixels = int(cfg.size[1] / cfg.horizontal_scale)
    amplitude_pixels = int(0.5 * amplitude / cfg.vertical_scale)

    # compute the wave number: nu = 2 * pi / lambda
    wave_length = length_pixels / cfg.num_waves
    wave_number = 2 * np.pi / wave_length
    # create meshgrid for the terrain
    x = np.arange(0, width_pixels)
    y = np.arange(0, length_pixels)
    xx, yy = np.meshgrid(x, y, sparse=True)
    xx = xx.reshape(width_pixels, 1)
    yy = yy.reshape(1, length_pixels)

    # create a terrain with a flat platform at the center
    hf_raw = np.zeros((width_pixels, length_pixels))
    # add the waves
    hf_raw += amplitude_pixels * (np.cos(yy * wave_number) + np.sin(xx * wave_number))
    # round off the heights to the nearest vertical step
    return np.rint(hf_raw).astype(np.int16)


@height_field_to_mesh
def random_uniform_terrain(difficulty: float, cfg: hf_terrains_cfg.HfRandomUniformTerrainCfg) -> np.ndarray:
    """Generate a terrain with height sampled uniformly from a specified range.

    .. image:: ../../_static/terrains/height_field/random_uniform_terrain.jpg
       :width: 40%
       :align: center

    Note:
        The :obj:`difficulty` parameter is ignored for this terrain.

    Args:
        difficulty: The difficulty of the terrain. This is a value between 0 and 1.
        cfg: The configuration for the terrain.

    Returns:
        The height field of the terrain as a 2D numpy array with discretized heights.
        The shape of the array is (width, length), where width and length are the number of points
        along the x and y axis, respectively.

    Raises:
        ValueError: When the downsampled scale is smaller than the horizontal scale.
    """
    # check parameters
    # -- horizontal scale
    if cfg.downsampled_scale is None:
        cfg.downsampled_scale = cfg.horizontal_scale
    elif cfg.downsampled_scale < cfg.horizontal_scale:
        raise ValueError(
            "Downsampled scale must be larger than or equal to the horizontal scale:"
            f" {cfg.downsampled_scale} < {cfg.horizontal_scale}."
        )

    # switch parameters to discrete units
    # -- horizontal scale
    width_pixels = int(cfg.size[0] / cfg.horizontal_scale)
    length_pixels = int(cfg.size[1] / cfg.horizontal_scale)
    # -- downsampled scale
    width_downsampled = int(cfg.size[0] / cfg.downsampled_scale)
    length_downsampled = int(cfg.size[1] / cfg.downsampled_scale)
    # -- height
    height_min = int(cfg.noise_range[0] / cfg.vertical_scale)
    height_max = int(cfg.noise_range[1] / cfg.vertical_scale)
    height_step = int(cfg.noise_step / cfg.vertical_scale)

    # create range of heights possible
    height_range = np.arange(height_min, height_max + height_step, height_step)
    # sample heights randomly from the range along a grid
    height_field_downsampled = np.random.choice(height_range, size=(width_downsampled, length_downsampled))
    # create interpolation function for the sampled heights
    x = np.linspace(0, cfg.size[0] * cfg.horizontal_scale, width_downsampled)
    y = np.linspace(0, cfg.size[1] * cfg.horizontal_scale, length_downsampled)
    func = interpolate.RectBivariateSpline(x, y, height_field_downsampled)

    # interpolate the sampled heights to obtain the height field
    x_upsampled = np.linspace(0, cfg.size[0] * cfg.horizontal_scale, width_pixels)
    y_upsampled = np.linspace(0, cfg.size[1] * cfg.horizontal_scale, length_pixels)
    z_upsampled = func(x_upsampled, y_upsampled)
    # round off the interpolated heights to the nearest vertical step
    return np.rint(z_upsampled).astype(np.int16)


def flat_terrain(
    difficulty: float, cfg: mesh_terrains_cfg.MeshPlaneTerrainCfg
):
    """Generate a flat terrain as a plane.

    .. image:: ../../_static/terrains/trimesh/flat_terrain.jpg
       :width: 45%
       :align: center

    Note:
        The :obj:`difficulty` parameter is ignored for this terrain.

    Args:
        difficulty: The difficulty of the terrain. This is a value between 0 and 1.
        cfg: The configuration for the terrain.

    Returns:
        A tuple containing the tri-mesh of the terrain and the origin of the terrain (in m).
    """
    # compute the position of the terrain
    origin = (cfg.size[0] / 2.0, cfg.size[1] / 2.0, 0.0)
    # compute the vertices of the terrain
    plane_mesh = make_plane(cfg.size, 0.0, center_zero=False)
    # return the tri-mesh and the position
    return [plane_mesh], np.array(origin), np.zeros((1, 1), dtype=np.int16)
